import Foundation

// Phase 3: Loads keyboard layouts from the JSON files generated by
// convert_keyboard_layouts.py.  The JSON files live in Layouts/ inside the
// keyboard extension bundle.
//
// Usage:
//   let layout = LayoutLoader.load("lime_phonetic") ?? .phonetic

final class LayoutLoader {

    // MARK: - JSON Codable types (mirrors the Python converter output)

    private struct JSONLayout: Decodable {
        let id: String
        let defaultWidthPercent: Double
        let rows: [JSONRow]
    }

    private struct JSONRow: Decodable {
        let isBottomRow: Bool
        let keys: [JSONKey]
    }

    private struct JSONKey: Decodable {
        let code: Int
        let label: String
        let sublabel: String
        let widthPercent: Double
        let icon: String
        let isModifier: Bool
        let isRepeatable: Bool
        let isSticky: Bool
        let popupKeyboard: String
        let longPressCode: Int?  // optional: nil if not present in JSON (old layouts)
    }

    // MARK: - Cache

    private static var cache: [String: LimeKeyLayout] = [:]
    private static let lock = NSLock()

    // MARK: - Public API

    /// Load a layout by ID (e.g. "lime_phonetic").
    /// Returns nil if the JSON file is not found or fails to parse.
    static func load(_ id: String) -> LimeKeyLayout? {
        lock.lock()
        if let cached = cache[id] { lock.unlock(); return cached }
        lock.unlock()

        guard let layout = parseFromBundle(id: id) else { return nil }

        lock.lock()
        cache[id] = layout
        lock.unlock()
        return layout
    }

    // MARK: - Private

    /// Splits an Android-style label string on the literal two-character sequence `\n`
    /// (backslash + n) that Android XML uses as a label/sublabel separator.
    /// If `label` contains no `\n`, returns (label, fallbackSublabel) unchanged.
    private static func splitLabel(_ label: String, fallbackSublabel: String) -> (String, String) {
        // JSON "1\\nㄅ" → Swift string where index 1 is '\' and index 2 is 'n'
        let sep = "\\" + "n"   // literal two chars: backslash + n
        if let range = label.range(of: sep) {
            let primary = String(label[label.startIndex..<range.lowerBound]).trimmingCharacters(in: .whitespaces)
            let sub     = String(label[range.upperBound...]).trimmingCharacters(in: .whitespaces)
            return (primary, sub)
        }
        return (label, fallbackSublabel)
    }

    private static func parseFromBundle(id: String) -> LimeKeyLayout? {
        // XcodeGen copies the Layouts/ folder contents flat into the bundle root.
        guard let url = Bundle.main.url(forResource: id, withExtension: "json"),
              let data = try? Data(contentsOf: url)
        else { return nil }

        let decoder = JSONDecoder()
        guard let json = try? decoder.decode(JSONLayout.self, from: data) else { return nil }

        let rows = json.rows.map { jr -> KeyRow in
            let keys = jr.keys.map { jk in
                // Android XML uses literal \n (backslash-n) as the label/sublabel separator,
                // e.g. keyLabel="1\nㄅ". Python's ET parser treats it as two chars (\ + n),
                // so the JSON stores "1\\nㄅ" → decoded Swift string "1\nㄅ" (backslash + n).
                // Split here so KeyDef always has separate label and sublabel fields.
                let (lbl, sub) = splitLabel(jk.label, fallbackSublabel: jk.sublabel)
                return KeyDef(
                    code:          jk.code,
                    label:         lbl,
                    sublabel:      sub,
                    widthPercent:  CGFloat(jk.widthPercent),
                    icon:          jk.icon,
                    isRepeatable:  jk.isRepeatable,
                    isModifier:    jk.isModifier,
                    isSticky:      jk.isSticky,
                    longPressCode: jk.longPressCode ?? 0
                )
            }
            return KeyRow(keys: keys, isBottomRow: jr.isBottomRow)
        }
        return LimeKeyLayout(id: id, rows: rows)
    }

    /// Pre-warm the cache for commonly used layouts in the background.
    static func prefetchCommonLayouts() {
        let ids = [
            "lime_phonetic", "lime_phonetic_shift",
            "lime_abc", "lime_abc_shift",
            "lime_number", "lime_number_symbol",
        ]
        DispatchQueue.global(qos: .background).async {
            for id in ids { _ = load(id) }
        }
    }
}
